### ISSUE TITLE
Can you share your ACCV paper?

### ISSUE THREAD

**Issue by carrierlxk** [sairin1202/Semantic-Aware-Attention-Based-Deep-Object-Co-segmentation#3]
Hi, I am very interested in your ACCV work, however I can not find the paper. So could you provide a camera ready pdf file? carrierlxk@126.com, thanks

**Comment by sairin1202** [comment]
I have uploaded the paper in arxiv. https://arxiv.org/abs/1810.06859
Thank you for your interests in our work.
