### ISSUE TITLE
ReadMe Drive Link Doesn't Work

### ISSUE THREAD

**Issue by Skylion007** [sairin1202/Semantic-Aware-Attention-Based-Deep-Object-Co-segmentation#4]
Hiya, the drive link for preprocessing dataset for the ReadMe does not work. (Unless you intend for everyone who wants to download to the dataset to request access).

Also would you be willing to release the pretrained weights for your network?

**Comment by sairin1202** [comment]
Sorry for my mistake, I have transferred the data into another google drive. 
if you are searching for a better result, you may have to retrain the model, for I have not finetuned this model.

**Comment by Skylion007** [comment]
I have tried to retrain the model several times, but I still can't get the results you got for group_demo.py in the ReadMe. Would you please share those pretrained weights?
