### ISSUE TITLE
What is the setting of your group co-segmentation experiments? How to construct the group co-segmentation dataset? randomly or pair all the images ? In your paper, I could not find the size of your group .Did you do the experiments with random group size or fixed group size? Thank you.

### ISSUE THREAD

**Issue by gengenkai** [sairin1202/Semantic-Aware-Attention-Based-Deep-Object-Co-segmentation#9]

**Comment by sairin1202** [comment]
Thank you for your interest in this work. We test this group co-segmentation method on several datasets. We directly pair all the images in one category to compare with the method that without this group co-segmentation.

**Comment by gengenkai** [comment]
Could you share your group co-segmentation code for reference? 
Thank you.

**Comment by sairin1202** [comment]
You can check the code in group_demo.py
